services:
  dbservice:
    image: postgres:17-alpine
    container_name: productportal-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: productportal
      POSTGRES_USER: productportal
      POSTGRES_PASSWORD: productportal
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
