-- PostgreSQL schema baseline for Product Portal.
-- Managed by Flyway. Do not use Hibernate ddl-auto to mutate production schema.

CREATE TABLE pp_m_role
(
    role_code    VARCHAR(30) NOT NULL,
    display_name VARCHAR(100)      NOT NULL,
    description  VARCHAR(255)      NULL,
    sort_order   INTEGER NOT NULL,
    is_active    BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by   VARCHAR(100)      NOT NULL DEFAULT 'SYSTEM',
    updated_at   TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by   VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_m_role PRIMARY KEY (role_code),
    CONSTRAINT uk_pp_m_role_display_name UNIQUE (display_name),
    CONSTRAINT chk_pp_m_role_code_not_blank
        CHECK (TRIM(role_code) <> ''),
    CONSTRAINT chk_pp_m_role_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_m_role_sort_order_positive
        CHECK (sort_order > 0)
);

CREATE TABLE pp_m_permission
(
    permission_code VARCHAR(80) NOT NULL,
    display_name    VARCHAR(150)      NOT NULL,
    description     VARCHAR(255)      NULL,
    resource_code   VARCHAR(60)       NOT NULL,
    action_code     VARCHAR(60)       NOT NULL,
    sort_order   INTEGER NOT NULL,
    is_active       BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by      VARCHAR(100)      NOT NULL DEFAULT 'SYSTEM',
    updated_at      TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by      VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_m_permission PRIMARY KEY (permission_code),
    CONSTRAINT uk_pp_m_permission_display_name UNIQUE (display_name),
    CONSTRAINT uk_pp_m_permission_resource_action UNIQUE (resource_code, action_code),
    CONSTRAINT chk_pp_m_permission_code_not_blank
        CHECK (TRIM(permission_code) <> ''),
    CONSTRAINT chk_pp_m_permission_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_m_permission_resource_code_not_blank
        CHECK (TRIM(resource_code) <> ''),
    CONSTRAINT chk_pp_m_permission_action_code_not_blank
        CHECK (TRIM(action_code) <> ''),
    CONSTRAINT chk_pp_m_permission_sort_order_positive
        CHECK (sort_order > 0)
);

CREATE TABLE pp_r_permission_scope
(
    scope_code   VARCHAR(30) NOT NULL,
    display_name VARCHAR(100)      NOT NULL,
    description  VARCHAR(255)      NULL,
    sort_order   INTEGER NOT NULL,
    is_active    BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by   VARCHAR(100)      NOT NULL DEFAULT 'SYSTEM',
    updated_at   TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by   VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_r_permission_scope PRIMARY KEY (scope_code),
    CONSTRAINT uk_pp_r_permission_scope_display_name UNIQUE (display_name),
    CONSTRAINT chk_pp_r_permission_scope_code_not_blank
        CHECK (TRIM(scope_code) <> ''),
    CONSTRAINT chk_pp_r_permission_scope_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_r_permission_scope_sort_order_positive
        CHECK (sort_order > 0)
);

CREATE TABLE pp_r_user_status
(
    status_code  VARCHAR(30) NOT NULL,
    display_name VARCHAR(100)      NOT NULL,
    description  VARCHAR(255)      NULL,
    sort_order   INTEGER NOT NULL,
    is_active    BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by   VARCHAR(100)      NOT NULL DEFAULT 'SYSTEM',
    updated_at   TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by   VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_r_user_status PRIMARY KEY (status_code),
    CONSTRAINT uk_pp_r_user_status_display_name UNIQUE (display_name),
    CONSTRAINT chk_pp_r_user_status_code_not_blank
        CHECK (TRIM(status_code) <> ''),
    CONSTRAINT chk_pp_r_user_status_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_r_user_status_sort_order_positive
        CHECK (sort_order > 0)
);

CREATE TABLE pp_m_organization
(
    organization_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_code VARCHAR(60) NOT NULL,
    display_name      VARCHAR(150)     NOT NULL,
    legal_name        VARCHAR(200)     NULL,
    description       VARCHAR(255)     NULL,
    is_active         BOOLEAN          NOT NULL DEFAULT TRUE,
    version           BIGINT  NOT NULL DEFAULT 0,
    created_at        TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by        VARCHAR(100)     NOT NULL DEFAULT 'SYSTEM',
    updated_at        TIMESTAMP(6)     NULL     DEFAULT NULL,
    updated_by        VARCHAR(100)     NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_m_organization PRIMARY KEY (organization_id),
    CONSTRAINT uk_pp_m_organization_code UNIQUE (organization_code),
    CONSTRAINT uk_pp_m_organization_display_name UNIQUE (display_name),
    CONSTRAINT chk_pp_m_organization_code_not_blank
        CHECK (TRIM(organization_code) <> ''),
    CONSTRAINT chk_pp_m_organization_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_m_organization_legal_name_not_blank
        CHECK (legal_name IS NULL OR TRIM(legal_name) <> '')
);

CREATE TABLE pp_r_membership_status
(
    status_code  VARCHAR(30) NOT NULL,
    display_name VARCHAR(100)      NOT NULL,
    description  VARCHAR(255)      NULL,
    sort_order   INTEGER NOT NULL,
    is_active    BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by   VARCHAR(100)      NOT NULL DEFAULT 'SYSTEM',
    updated_at   TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by   VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_r_membership_status PRIMARY KEY (status_code),
    CONSTRAINT uk_pp_r_membership_status_display_name UNIQUE (display_name),
    CONSTRAINT chk_pp_r_membership_status_code_not_blank
        CHECK (TRIM(status_code) <> ''),
    CONSTRAINT chk_pp_r_membership_status_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_r_membership_status_sort_order_positive
        CHECK (sort_order > 0)
);

CREATE TABLE pp_m_user
(
    user_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(100)    NOT NULL,
    full_name               VARCHAR(150)    NOT NULL,
    email                   VARCHAR(254)    NOT NULL,
    phone_number            VARCHAR(30)     NULL,
    password_hash           VARCHAR(255)    NOT NULL,
    credentials_changed_at  TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    status                  VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    primary_organization_id BIGINT NULL     DEFAULT NULL,
    version                 BIGINT NOT NULL DEFAULT 0,
    created_at              TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by              VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    updated_at              TIMESTAMP(6)    NULL     DEFAULT NULL,
    updated_by              VARCHAR(100)    NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_m_user PRIMARY KEY (user_id),
    CONSTRAINT uk_pp_m_user_username UNIQUE (username),
    CONSTRAINT uk_pp_m_user_email UNIQUE (email),
    CONSTRAINT uk_pp_m_user_phone_number UNIQUE (phone_number),
    CONSTRAINT fk_pp_m_user_status
        FOREIGN KEY (status) REFERENCES pp_r_user_status (status_code),
    CONSTRAINT fk_pp_m_user_primary_organization
        FOREIGN KEY (primary_organization_id) REFERENCES pp_m_organization (organization_id) ON DELETE SET NULL,
    CONSTRAINT chk_pp_m_user_full_name_not_blank
        CHECK (TRIM(full_name) <> ''),
    CONSTRAINT chk_pp_m_user_username_not_blank
        CHECK (TRIM(username) <> ''),
    CONSTRAINT chk_pp_m_user_email_not_blank
        CHECK (TRIM(email) <> ''),
    CONSTRAINT chk_pp_m_user_password_hash_not_blank
        CHECK (TRIM(password_hash) <> ''),
    CONSTRAINT chk_pp_m_user_phone_number_not_blank
        CHECK (phone_number IS NULL OR TRIM(phone_number) <> '')
);

CREATE TABLE pp_t_auth_session
(
    auth_session_id     CHAR(36)        NOT NULL,
    user_id             BIGINT NOT NULL,
    refresh_token_hash  VARCHAR(64)        NOT NULL,
    issued_at           TIMESTAMP(6)    NOT NULL,
    refresh_expires_at  TIMESTAMP(6)    NOT NULL,
    last_used_at        TIMESTAMP(6)    NOT NULL,
    revoked_at          TIMESTAMP(6)    NULL     DEFAULT NULL,
    revocation_reason   VARCHAR(60)     NULL     DEFAULT NULL,
    client_ip           VARCHAR(45)     NULL     DEFAULT NULL,
    user_agent          VARCHAR(512)    NULL     DEFAULT NULL,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by          VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    updated_at          TIMESTAMP(6)    NULL     DEFAULT NULL,
    updated_by          VARCHAR(100)    NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_t_auth_session PRIMARY KEY (auth_session_id),
    CONSTRAINT fk_pp_t_auth_session_user
        FOREIGN KEY (user_id) REFERENCES pp_m_user (user_id) ON DELETE CASCADE,
    CONSTRAINT chk_pp_t_auth_session_refresh_token_hash_not_blank
        CHECK (TRIM(refresh_token_hash) <> ''),
    CONSTRAINT chk_pp_t_auth_session_refresh_window
        CHECK (refresh_expires_at > issued_at),
    CONSTRAINT chk_pp_t_auth_session_last_used_window
        CHECK (last_used_at >= issued_at),
    CONSTRAINT chk_pp_t_auth_session_revocation_reason
        CHECK (revocation_reason IS NULL OR revocation_reason IN (
            'LOGOUT',
            'REFRESH_TOKEN_REUSE_DETECTED',
            'PASSWORD_CHANGED',
            'SESSION_LIMIT_EXCEEDED',
            'ADMIN_REVOKED'
        )),
    CONSTRAINT chk_pp_t_auth_session_client_ip_not_blank
        CHECK (client_ip IS NULL OR TRIM(client_ip) <> ''),
    CONSTRAINT chk_pp_t_auth_session_user_agent_not_blank
        CHECK (user_agent IS NULL OR TRIM(user_agent) <> ''),
    CONSTRAINT chk_pp_t_auth_session_created_by_not_blank
        CHECK (TRIM(created_by) <> '')
);

CREATE TABLE pp_t_login_throttle_state
(
    throttle_state_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    scope                VARCHAR(30)     NOT NULL,
    identifier_value     VARCHAR(255)    NOT NULL,
    failed_attempt_count INT             NOT NULL DEFAULT 0,
    window_started_at    TIMESTAMP(6)    NULL     DEFAULT NULL,
    last_failed_at       TIMESTAMP(6)    NULL     DEFAULT NULL,
    locked_until         TIMESTAMP(6)    NULL     DEFAULT NULL,
    last_successful_at   TIMESTAMP(6)    NULL     DEFAULT NULL,
    version              BIGINT NOT NULL DEFAULT 0,
    created_at           TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by           VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    updated_at           TIMESTAMP(6)    NULL     DEFAULT NULL,
    updated_by           VARCHAR(100)    NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_t_login_throttle_state PRIMARY KEY (throttle_state_id),
    CONSTRAINT uk_pp_t_login_throttle_state_scope_identifier
        UNIQUE (scope, identifier_value),
    CONSTRAINT chk_pp_t_login_throttle_state_scope
        CHECK (scope IN ('USERNAME', 'IP_ADDRESS')),
    CONSTRAINT chk_pp_t_login_throttle_state_identifier_not_blank
        CHECK (TRIM(identifier_value) <> ''),
    CONSTRAINT chk_pp_t_login_throttle_state_failed_attempt_count
        CHECK (failed_attempt_count >= 0),
    CONSTRAINT chk_pp_t_login_throttle_state_created_by_not_blank
        CHECK (TRIM(created_by) <> '')
);

CREATE TABLE pp_a_login_attempt
(
    login_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         VARCHAR(100)    NOT NULL,
    user_id          BIGINT NULL,
    outcome          VARCHAR(40)     NOT NULL,
    client_ip        VARCHAR(45)     NULL,
    user_agent       VARCHAR(512)    NULL,
    locked_until     TIMESTAMP(6)    NULL     DEFAULT NULL,
    occurred_at      TIMESTAMP(6)    NOT NULL,
    created_at       TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by       VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT pk_pp_a_login_attempt PRIMARY KEY (login_attempt_id),
    CONSTRAINT fk_pp_a_login_attempt_user
        FOREIGN KEY (user_id) REFERENCES pp_m_user (user_id) ON DELETE SET NULL,
    CONSTRAINT chk_pp_a_login_attempt_username_not_blank
        CHECK (TRIM(username) <> ''),
    CONSTRAINT chk_pp_a_login_attempt_outcome
        CHECK (outcome IN (
            'SUCCESS',
            'BAD_CREDENTIALS',
            'ACCOUNT_DISABLED',
            'NO_ACTIVE_ROLE_ASSIGNMENT',
            'USERNAME_LOCKED',
            'IP_THROTTLED'
        )),
    CONSTRAINT chk_pp_a_login_attempt_client_ip_not_blank
        CHECK (client_ip IS NULL OR TRIM(client_ip) <> ''),
    CONSTRAINT chk_pp_a_login_attempt_user_agent_not_blank
        CHECK (user_agent IS NULL OR TRIM(user_agent) <> ''),
    CONSTRAINT chk_pp_a_login_attempt_created_by_not_blank
        CHECK (TRIM(created_by) <> '')
);

CREATE TABLE pp_t_user_organization_membership
(
    user_id           BIGINT NOT NULL,
    organization_id   BIGINT NOT NULL,
    membership_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    is_primary        BOOLEAN         NOT NULL DEFAULT FALSE,
    joined_at         TIMESTAMP(6)    NULL     DEFAULT NULL,
    invited_by        VARCHAR(100)    NULL     DEFAULT NULL,
    invited_at        TIMESTAMP(6)    NULL     DEFAULT NULL,
    created_at        TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by        VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    updated_at        TIMESTAMP(6)    NULL     DEFAULT NULL,
    updated_by        VARCHAR(100)    NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_t_user_organization_membership PRIMARY KEY (user_id, organization_id),
    CONSTRAINT fk_pp_t_user_organization_membership_user
        FOREIGN KEY (user_id) REFERENCES pp_m_user (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_pp_t_user_organization_membership_organization
        FOREIGN KEY (organization_id) REFERENCES pp_m_organization (organization_id),
    CONSTRAINT fk_pp_t_user_organization_membership_status
        FOREIGN KEY (membership_status) REFERENCES pp_r_membership_status (status_code),
    CONSTRAINT chk_pp_t_user_organization_membership_invited_by_not_blank
        CHECK (invited_by IS NULL OR TRIM(invited_by) <> '')
);

CREATE TABLE pp_t_user_role_assignment
(
    user_id    BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 1,
    role_code  VARCHAR(30) NOT NULL,
    is_active  BOOLEAN         NOT NULL DEFAULT TRUE,
    valid_from TIMESTAMP(6)    NULL     DEFAULT NULL,
    valid_until TIMESTAMP(6)   NULL     DEFAULT NULL,
    assigned_by VARCHAR(100)   NOT NULL DEFAULT 'SYSTEM',
    assigned_reason VARCHAR(255) NULL,
    revoked_by VARCHAR(100)    NULL     DEFAULT NULL,
    revoked_reason VARCHAR(255) NULL,
    created_at TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    updated_at TIMESTAMP(6)    NULL     DEFAULT NULL,
    updated_by VARCHAR(100)    NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_t_user_role_assignment PRIMARY KEY (user_id, organization_id, role_code),
    CONSTRAINT fk_pp_t_user_role_assignment_user
        FOREIGN KEY (user_id) REFERENCES pp_m_user (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_pp_t_user_role_assignment_organization
        FOREIGN KEY (organization_id) REFERENCES pp_m_organization (organization_id),
    CONSTRAINT fk_pp_t_user_role_assignment_membership
        FOREIGN KEY (user_id, organization_id) REFERENCES pp_t_user_organization_membership (user_id, organization_id),
    CONSTRAINT fk_pp_t_user_role_assignment_role
        FOREIGN KEY (role_code) REFERENCES pp_m_role (role_code),
    CONSTRAINT chk_pp_t_user_role_assignment_role_code_not_blank
        CHECK (TRIM(role_code) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_valid_window
        CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from),
    CONSTRAINT chk_pp_t_user_role_assignment_assigned_by_not_blank
        CHECK (TRIM(assigned_by) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_assigned_reason_not_blank
        CHECK (assigned_reason IS NULL OR TRIM(assigned_reason) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_revoked_by_not_blank
        CHECK (revoked_by IS NULL OR TRIM(revoked_by) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_revoked_reason_not_blank
        CHECK (revoked_reason IS NULL OR TRIM(revoked_reason) <> '')
);

CREATE TABLE pp_t_role_permission_grant
(
    role_code       VARCHAR(30) NOT NULL,
    permission_code VARCHAR(80) NOT NULL,
    scope_code      VARCHAR(30) NOT NULL DEFAULT 'ORGANIZATION',
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    assigned_by     VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    assigned_reason VARCHAR(255) NULL,
    revoked_by      VARCHAR(100) NULL     DEFAULT NULL,
    revoked_reason  VARCHAR(255) NULL,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by      VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at      TIMESTAMP(6) NULL     DEFAULT NULL,
    updated_by      VARCHAR(100) NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_t_role_permission_grant PRIMARY KEY (role_code, permission_code),
    CONSTRAINT fk_pp_t_role_permission_grant_role
        FOREIGN KEY (role_code) REFERENCES pp_m_role (role_code),
    CONSTRAINT fk_pp_t_role_permission_grant_permission
        FOREIGN KEY (permission_code) REFERENCES pp_m_permission (permission_code),
    CONSTRAINT fk_pp_t_role_permission_grant_scope
        FOREIGN KEY (scope_code) REFERENCES pp_r_permission_scope (scope_code),
    CONSTRAINT chk_pp_t_role_permission_grant_role_code_not_blank
        CHECK (TRIM(role_code) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_permission_code_not_blank
        CHECK (TRIM(permission_code) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_scope_code_not_blank
        CHECK (TRIM(scope_code) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_assigned_by_not_blank
        CHECK (TRIM(assigned_by) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_assigned_reason_not_blank
        CHECK (assigned_reason IS NULL OR TRIM(assigned_reason) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_revoked_by_not_blank
        CHECK (revoked_by IS NULL OR TRIM(revoked_by) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_revoked_reason_not_blank
        CHECK (revoked_reason IS NULL OR TRIM(revoked_reason) <> '')
);

CREATE TABLE pp_t_user_organization_membership_audit
(
    audit_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                    BIGINT NOT NULL,
    organization_id            BIGINT NOT NULL,
    event_type                 VARCHAR(30)     NOT NULL,
    previous_membership_status VARCHAR(30) NULL DEFAULT NULL,
    new_membership_status      VARCHAR(30) NULL DEFAULT NULL,
    previous_primary           BOOLEAN         NULL,
    new_primary                BOOLEAN         NULL,
    previous_joined_at         TIMESTAMP(6)    NULL DEFAULT NULL,
    new_joined_at              TIMESTAMP(6)    NULL DEFAULT NULL,
    previous_invited_by        VARCHAR(100)    NULL DEFAULT NULL,
    new_invited_by             VARCHAR(100)    NULL DEFAULT NULL,
    previous_invited_at        TIMESTAMP(6)    NULL DEFAULT NULL,
    new_invited_at             TIMESTAMP(6)    NULL DEFAULT NULL,
    changed_at                 TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    changed_by                 VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    database_user              VARCHAR(100)    NOT NULL DEFAULT 'UNKNOWN',
    source_code                VARCHAR(30)     NOT NULL DEFAULT 'DATABASE_TRIGGER',
    change_reason              VARCHAR(255)    NULL,
    correlation_id             VARCHAR(100)    NULL,

    CONSTRAINT pk_pp_t_user_organization_membership_audit PRIMARY KEY (audit_id),
    CONSTRAINT chk_pp_t_user_organization_membership_audit_event_type
        CHECK (event_type IN ('INVITED', 'JOINED', 'ACTIVATED', 'SUSPENDED', 'LEFT', 'REMOVED',
                              'PRIMARY_CHANGED', 'DETAILS_CHANGED', 'MIGRATED')),
    CONSTRAINT chk_pp_t_user_org_mship_aud_prev_status_nb
        CHECK (previous_membership_status IS NULL OR TRIM(previous_membership_status) <> ''),
    CONSTRAINT chk_pp_t_user_org_mship_aud_new_status_nb
        CHECK (new_membership_status IS NULL OR TRIM(new_membership_status) <> ''),
    CONSTRAINT chk_pp_t_user_org_mship_aud_changed_by_nb
        CHECK (TRIM(changed_by) <> ''),
    CONSTRAINT chk_pp_t_user_org_mship_aud_db_user_nb
        CHECK (TRIM(database_user) <> ''),
    CONSTRAINT chk_pp_t_user_org_mship_aud_source_nb
        CHECK (TRIM(source_code) <> ''),
    CONSTRAINT chk_pp_t_user_org_mship_aud_prev_inv_by_nb
        CHECK (previous_invited_by IS NULL OR TRIM(previous_invited_by) <> ''),
    CONSTRAINT chk_pp_t_user_org_mship_aud_new_inv_by_nb
        CHECK (new_invited_by IS NULL OR TRIM(new_invited_by) <> '')
);

CREATE TABLE pp_t_user_role_assignment_audit
(
    audit_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    role_code       VARCHAR(30) NOT NULL,
    event_type      VARCHAR(30)     NOT NULL,
    previous_active BOOLEAN         NULL,
    new_active      BOOLEAN         NULL,
    previous_valid_from  TIMESTAMP(6) NULL DEFAULT NULL,
    previous_valid_until TIMESTAMP(6) NULL DEFAULT NULL,
    new_valid_from       TIMESTAMP(6) NULL DEFAULT NULL,
    new_valid_until      TIMESTAMP(6) NULL DEFAULT NULL,
    assigned_by     VARCHAR(100)    NULL     DEFAULT NULL,
    assigned_reason VARCHAR(255)    NULL,
    revoked_by      VARCHAR(100)    NULL     DEFAULT NULL,
    revoked_reason  VARCHAR(255)    NULL,
    changed_at      TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    changed_by      VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    database_user   VARCHAR(100)    NOT NULL DEFAULT 'UNKNOWN',
    source_code     VARCHAR(30)     NOT NULL DEFAULT 'DATABASE_TRIGGER',
    change_reason   VARCHAR(255)    NULL,
    correlation_id  VARCHAR(100)    NULL,

    CONSTRAINT pk_pp_t_user_role_assignment_audit PRIMARY KEY (audit_id),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_role_code_not_blank
        CHECK (TRIM(role_code) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_event_type
        CHECK (event_type IN ('ASSIGNED', 'ACTIVATED', 'DEACTIVATED', 'VALIDITY_CHANGED', 'REVOKED', 'MIGRATED')),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_changed_by_not_blank
        CHECK (TRIM(changed_by) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_database_user_not_blank
        CHECK (TRIM(database_user) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_source_code_not_blank
        CHECK (TRIM(source_code) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_assigned_by_not_blank
        CHECK (assigned_by IS NULL OR TRIM(assigned_by) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_assigned_reason_not_blank
        CHECK (assigned_reason IS NULL OR TRIM(assigned_reason) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_revoked_by_not_blank
        CHECK (revoked_by IS NULL OR TRIM(revoked_by) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_revoked_reason_not_blank
        CHECK (revoked_reason IS NULL OR TRIM(revoked_reason) <> ''),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_previous_valid_window
        CHECK (previous_valid_until IS NULL OR previous_valid_from IS NULL OR previous_valid_until > previous_valid_from),
    CONSTRAINT chk_pp_t_user_role_assignment_audit_new_valid_window
        CHECK (new_valid_until IS NULL OR new_valid_from IS NULL OR new_valid_until > new_valid_from)
);

CREATE TABLE pp_t_role_permission_grant_audit
(
    audit_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_code       VARCHAR(30) NOT NULL,
    permission_code VARCHAR(80) NOT NULL,
    event_type      VARCHAR(30)     NOT NULL,
    previous_active BOOLEAN         NULL,
    new_active      BOOLEAN         NULL,
    previous_scope_code VARCHAR(30) NULL DEFAULT NULL,
    new_scope_code      VARCHAR(30) NULL DEFAULT NULL,
    assigned_by     VARCHAR(100)    NULL     DEFAULT NULL,
    assigned_reason VARCHAR(255)    NULL,
    revoked_by      VARCHAR(100)    NULL     DEFAULT NULL,
    revoked_reason  VARCHAR(255)    NULL,
    changed_at      TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    changed_by      VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    database_user   VARCHAR(100)    NOT NULL DEFAULT 'UNKNOWN',
    source_code     VARCHAR(30)     NOT NULL DEFAULT 'DATABASE_TRIGGER',
    change_reason   VARCHAR(255)    NULL,
    correlation_id  VARCHAR(100)    NULL,

    CONSTRAINT pk_pp_t_role_permission_grant_audit PRIMARY KEY (audit_id),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_role_code_not_blank
        CHECK (TRIM(role_code) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_permission_code_not_blank
        CHECK (TRIM(permission_code) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_event_type
        CHECK (event_type IN ('ASSIGNED', 'ACTIVATED', 'DEACTIVATED', 'SCOPE_CHANGED', 'REVOKED', 'MIGRATED')),
    CONSTRAINT chk_pp_t_role_perm_grant_aud_prev_scope_nb
        CHECK (previous_scope_code IS NULL OR TRIM(previous_scope_code) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_new_scope_code_not_blank
        CHECK (new_scope_code IS NULL OR TRIM(new_scope_code) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_changed_by_not_blank
        CHECK (TRIM(changed_by) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_database_user_not_blank
        CHECK (TRIM(database_user) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_source_code_not_blank
        CHECK (TRIM(source_code) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_assigned_by_not_blank
        CHECK (assigned_by IS NULL OR TRIM(assigned_by) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_assigned_reason_not_blank
        CHECK (assigned_reason IS NULL OR TRIM(assigned_reason) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_revoked_by_not_blank
        CHECK (revoked_by IS NULL OR TRIM(revoked_by) <> ''),
    CONSTRAINT chk_pp_t_role_permission_grant_audit_revoked_reason_not_blank
        CHECK (revoked_reason IS NULL OR TRIM(revoked_reason) <> '')
);

CREATE TABLE pp_m_user_address
(
    address_id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                 BIGINT NOT NULL,
    recipient_name          VARCHAR(150)    NOT NULL,
    phone_number            VARCHAR(30)     NOT NULL,
    address_line_1          VARCHAR(255)    NOT NULL,
    address_line_2          VARCHAR(255)    NULL,
    city                    VARCHAR(100)    NOT NULL,
    district                VARCHAR(100)    NULL,
    province                VARCHAR(100)    NULL,
    postal_code             VARCHAR(20)     NULL,
    country                 VARCHAR(100)    NOT NULL,
    is_default              BOOLEAN         NOT NULL DEFAULT FALSE,
    version                 BIGINT NOT NULL DEFAULT 0,
    created_at              TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by              VARCHAR(100)    NOT NULL DEFAULT 'SYSTEM',
    updated_at              TIMESTAMP(6)    NULL     DEFAULT NULL,
    updated_by              VARCHAR(100)    NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_m_user_address PRIMARY KEY (address_id),
    CONSTRAINT fk_pp_m_user_address_user
        FOREIGN KEY (user_id) REFERENCES pp_m_user (user_id) ON DELETE CASCADE,
    CONSTRAINT chk_pp_m_user_address_recipient_name_not_blank
        CHECK (TRIM(recipient_name) <> ''),
    CONSTRAINT chk_pp_m_user_address_phone_number_not_blank
        CHECK (TRIM(phone_number) <> ''),
    CONSTRAINT chk_pp_m_user_address_address_line_1_not_blank
        CHECK (TRIM(address_line_1) <> ''),
    CONSTRAINT chk_pp_m_user_address_city_not_blank
        CHECK (TRIM(city) <> ''),
    CONSTRAINT chk_pp_m_user_address_country_not_blank
        CHECK (TRIM(country) <> ''),
    CONSTRAINT chk_pp_m_user_address_address_line_2_not_blank
        CHECK (address_line_2 IS NULL OR TRIM(address_line_2) <> ''),
    CONSTRAINT chk_pp_m_user_address_district_not_blank
        CHECK (district IS NULL OR TRIM(district) <> ''),
    CONSTRAINT chk_pp_m_user_address_province_not_blank
        CHECK (province IS NULL OR TRIM(province) <> ''),
    CONSTRAINT chk_pp_m_user_address_postal_code_not_blank
        CHECK (postal_code IS NULL OR TRIM(postal_code) <> '')
);

CREATE TABLE pp_r_category_status
(
    status_code  VARCHAR(30)       NOT NULL,
    display_name VARCHAR(100)      NOT NULL,
    description  VARCHAR(255)      NULL,
    sort_order   INTEGER NOT NULL,
    is_active    BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by   VARCHAR(100)      NOT NULL DEFAULT 'SYSTEM',
    updated_at   TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by   VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_r_category_status PRIMARY KEY (status_code),
    CONSTRAINT uk_pp_r_category_status_display_name UNIQUE (display_name),
    CONSTRAINT chk_pp_r_category_status_code_not_blank
        CHECK (TRIM(status_code) <> ''),
    CONSTRAINT chk_pp_r_category_status_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_r_category_status_sort_order_positive
        CHECK (sort_order > 0)
);

CREATE TABLE pp_r_brand_status
(
    status_code  VARCHAR(30)       NOT NULL,
    display_name VARCHAR(100)      NOT NULL,
    description  VARCHAR(255)      NULL,
    sort_order   INTEGER NOT NULL,
    is_active    BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by   VARCHAR(100)      NOT NULL DEFAULT 'SYSTEM',
    updated_at   TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by   VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_r_brand_status PRIMARY KEY (status_code),
    CONSTRAINT uk_pp_r_brand_status_display_name UNIQUE (display_name),
    CONSTRAINT chk_pp_r_brand_status_code_not_blank
        CHECK (TRIM(status_code) <> ''),
    CONSTRAINT chk_pp_r_brand_status_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_r_brand_status_sort_order_positive
        CHECK (sort_order > 0)
);

CREATE TABLE pp_r_product_status
(
    status_code  VARCHAR(30)       NOT NULL,
    display_name VARCHAR(100)      NOT NULL,
    description  VARCHAR(255)      NULL,
    sort_order   INTEGER NOT NULL,
    is_active    BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by   VARCHAR(100)      NOT NULL DEFAULT 'SYSTEM',
    updated_at   TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by   VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_r_product_status PRIMARY KEY (status_code),
    CONSTRAINT uk_pp_r_product_status_display_name UNIQUE (display_name),
    CONSTRAINT chk_pp_r_product_status_code_not_blank
        CHECK (TRIM(status_code) <> ''),
    CONSTRAINT chk_pp_r_product_status_display_name_not_blank
        CHECK (TRIM(display_name) <> ''),
    CONSTRAINT chk_pp_r_product_status_sort_order_positive
        CHECK (sort_order > 0)
);

CREATE TABLE pp_m_category
(
    category_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_category_id BIGINT   NULL,
    name               VARCHAR(150)      NOT NULL,
    slug               VARCHAR(180)      NOT NULL,
    status_code        VARCHAR(30)       NOT NULL DEFAULT 'ACTIVE',
    sort_order   INTEGER NOT NULL DEFAULT 0,
    version            BIGINT   NOT NULL DEFAULT 0,
    created_at         TIMESTAMP(6)      NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by         VARCHAR(100)      NOT NULL,
    updated_at         TIMESTAMP(6)      NULL     DEFAULT NULL,
    updated_by         VARCHAR(100)      NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_m_category PRIMARY KEY (category_id),
    CONSTRAINT uk_pp_m_category_slug UNIQUE (slug),
    CONSTRAINT fk_pp_m_category_parent
        FOREIGN KEY (parent_category_id) REFERENCES pp_m_category (category_id),
    CONSTRAINT fk_pp_m_category_status
        FOREIGN KEY (status_code) REFERENCES pp_r_category_status (status_code),
    CONSTRAINT chk_pp_m_category_name_not_blank
        CHECK (TRIM(name) <> ''),
    CONSTRAINT chk_pp_m_category_slug_not_blank
        CHECK (TRIM(slug) <> '')
);

CREATE TABLE pp_m_brand
(
    brand_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(150)    NOT NULL,
    slug        VARCHAR(180)    NOT NULL,
    description TEXT            NULL,
    logo_url    VARCHAR(500)    NULL,
    status_code VARCHAR(30)     NOT NULL DEFAULT 'ACTIVE',
    version     BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by  VARCHAR(100)    NOT NULL,
    updated_at  TIMESTAMP(6)    NULL     DEFAULT NULL,
    updated_by  VARCHAR(100)    NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_m_brand PRIMARY KEY (brand_id),
    CONSTRAINT uk_pp_m_brand_name UNIQUE (name),
    CONSTRAINT uk_pp_m_brand_slug UNIQUE (slug),
    CONSTRAINT fk_pp_m_brand_status
        FOREIGN KEY (status_code) REFERENCES pp_r_brand_status (status_code),
    CONSTRAINT chk_pp_m_brand_name_not_blank
        CHECK (TRIM(name) <> ''),
    CONSTRAINT chk_pp_m_brand_slug_not_blank
        CHECK (TRIM(slug) <> '')
);

CREATE TABLE pp_m_product
(
    product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 1,
    owner_user_id BIGINT NULL,
    category_id  BIGINT NOT NULL,
    brand_id     BIGINT NULL,
    name         VARCHAR(255)    NOT NULL,
    slug         VARCHAR(300)    NOT NULL,
    description  TEXT            NULL,
    model_number VARCHAR(100)    NULL,
    sku_code     VARCHAR(100)    NULL,
    status_code  VARCHAR(30)     NOT NULL DEFAULT 'DRAFT',
    version      BIGINT NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by   VARCHAR(100)    NOT NULL,
    updated_at   TIMESTAMP(6)    NULL     DEFAULT NULL,
    updated_by   VARCHAR(100)    NULL     DEFAULT NULL,

    CONSTRAINT pk_pp_m_product PRIMARY KEY (product_id),
    CONSTRAINT uk_pp_m_product_org_slug UNIQUE (organization_id, slug),
    CONSTRAINT uk_pp_m_product_org_sku_code UNIQUE (organization_id, sku_code),
    CONSTRAINT fk_pp_m_product_organization
        FOREIGN KEY (organization_id) REFERENCES pp_m_organization (organization_id),
    CONSTRAINT fk_pp_m_product_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES pp_m_user (user_id) ON DELETE SET NULL,
    CONSTRAINT fk_pp_m_product_category
        FOREIGN KEY (category_id) REFERENCES pp_m_category (category_id),
    CONSTRAINT fk_pp_m_product_brand
        FOREIGN KEY (brand_id) REFERENCES pp_m_brand (brand_id),
    CONSTRAINT fk_pp_m_product_status
        FOREIGN KEY (status_code) REFERENCES pp_r_product_status (status_code),
    CONSTRAINT chk_pp_m_product_name_not_blank
        CHECK (TRIM(name) <> ''),
    CONSTRAINT chk_pp_m_product_slug_not_blank
        CHECK (TRIM(slug) <> '')
);


-- PostgreSQL indexes extracted from MySQL inline INDEX declarations.

CREATE INDEX idx_pp_m_permission_active ON pp_m_permission (is_active);
CREATE INDEX idx_pp_r_permission_scope_active ON pp_r_permission_scope (is_active);
CREATE INDEX idx_pp_m_organization_active ON pp_m_organization (is_active);
CREATE INDEX idx_pp_m_user_status ON pp_m_user (status);
CREATE INDEX idx_pp_m_user_primary_organization_id ON pp_m_user (primary_organization_id);
CREATE INDEX idx_pp_t_auth_session_user_active ON pp_t_auth_session (user_id, revoked_at, refresh_expires_at);
CREATE INDEX idx_pp_t_auth_session_refresh_expires_at ON pp_t_auth_session (refresh_expires_at);
CREATE INDEX idx_pp_t_login_throttle_state_scope_locked_until ON pp_t_login_throttle_state (scope, locked_until);
CREATE INDEX idx_pp_t_login_throttle_state_identifier ON pp_t_login_throttle_state (identifier_value);
CREATE INDEX idx_pp_a_login_attempt_username_time ON pp_a_login_attempt (username, occurred_at);
CREATE INDEX idx_pp_a_login_attempt_client_ip_time ON pp_a_login_attempt (client_ip, occurred_at);
CREATE INDEX idx_pp_a_login_attempt_outcome_time ON pp_a_login_attempt (outcome, occurred_at);
CREATE INDEX idx_pp_a_login_attempt_user_id_time ON pp_a_login_attempt (user_id, occurred_at);
CREATE INDEX idx_pp_t_user_organization_membership_status ON pp_t_user_organization_membership (membership_status);
CREATE INDEX idx_pp_t_user_organization_membership_org_status ON pp_t_user_organization_membership (organization_id, membership_status);
CREATE INDEX idx_pp_t_user_organization_membership_user_status ON pp_t_user_organization_membership (user_id, membership_status);
CREATE INDEX idx_pp_t_user_organization_membership_primary ON pp_t_user_organization_membership (user_id, is_primary);
CREATE UNIQUE INDEX uk_pp_t_user_org_membership_one_primary ON pp_t_user_organization_membership (user_id) WHERE is_primary;
CREATE INDEX idx_pp_t_user_organization_membership_invited_by ON pp_t_user_organization_membership (invited_by);
CREATE INDEX idx_pp_t_user_role_assignment_role_code ON pp_t_user_role_assignment (role_code);
CREATE INDEX idx_pp_t_user_role_assignment_user_org_active_validity ON pp_t_user_role_assignment (user_id, organization_id, is_active, valid_from, valid_until);
CREATE INDEX idx_pp_t_user_role_assignment_org_role_active ON pp_t_user_role_assignment (organization_id, role_code, is_active);
CREATE INDEX idx_pp_t_user_role_assignment_role_active ON pp_t_user_role_assignment (role_code, is_active);
CREATE INDEX idx_pp_t_user_role_assignment_assigned_by ON pp_t_user_role_assignment (assigned_by);
CREATE INDEX idx_pp_t_user_role_assignment_revoked_by ON pp_t_user_role_assignment (revoked_by);
CREATE INDEX idx_pp_t_role_permission_grant_permission_code ON pp_t_role_permission_grant (permission_code);
CREATE INDEX idx_pp_t_role_permission_grant_scope_code ON pp_t_role_permission_grant (scope_code);
CREATE INDEX idx_pp_t_role_permission_grant_role_active ON pp_t_role_permission_grant (role_code, is_active);
CREATE INDEX idx_pp_t_role_permission_grant_permission_scope_active ON pp_t_role_permission_grant (permission_code, scope_code, is_active);
CREATE INDEX idx_pp_t_role_permission_grant_permission_active ON pp_t_role_permission_grant (permission_code, is_active);
CREATE INDEX idx_pp_t_role_permission_grant_assigned_by ON pp_t_role_permission_grant (assigned_by);
CREATE INDEX idx_pp_t_role_permission_grant_revoked_by ON pp_t_role_permission_grant (revoked_by);
CREATE INDEX idx_pp_t_user_organization_membership_audit_user_org_time ON pp_t_user_organization_membership_audit (user_id, organization_id, changed_at);
CREATE INDEX idx_pp_t_user_organization_membership_audit_org_time ON pp_t_user_organization_membership_audit (organization_id, changed_at);
CREATE INDEX idx_pp_t_user_organization_membership_audit_event_time ON pp_t_user_organization_membership_audit (event_type, changed_at);
CREATE INDEX idx_pp_t_user_organization_membership_audit_correlation_id ON pp_t_user_organization_membership_audit (correlation_id);
CREATE INDEX idx_pp_t_user_organization_membership_audit_changed_by ON pp_t_user_organization_membership_audit (changed_by);
CREATE INDEX idx_pp_t_user_role_assignment_audit_user_org_time ON pp_t_user_role_assignment_audit (user_id, organization_id, changed_at);
CREATE INDEX idx_pp_t_user_role_assignment_audit_org_time ON pp_t_user_role_assignment_audit (organization_id, changed_at);
CREATE INDEX idx_pp_t_user_role_assignment_audit_role_time ON pp_t_user_role_assignment_audit (role_code, changed_at);
CREATE INDEX idx_pp_t_user_role_assignment_audit_event_time ON pp_t_user_role_assignment_audit (event_type, changed_at);
CREATE INDEX idx_pp_t_user_role_assignment_audit_correlation_id ON pp_t_user_role_assignment_audit (correlation_id);
CREATE INDEX idx_pp_t_user_role_assignment_audit_assigned_by ON pp_t_user_role_assignment_audit (assigned_by);
CREATE INDEX idx_pp_t_user_role_assignment_audit_revoked_by ON pp_t_user_role_assignment_audit (revoked_by);
CREATE INDEX idx_pp_t_role_permission_grant_audit_role_time ON pp_t_role_permission_grant_audit (role_code, changed_at);
CREATE INDEX idx_pp_t_role_permission_grant_audit_permission_time ON pp_t_role_permission_grant_audit (permission_code, changed_at);
CREATE INDEX idx_pp_t_role_permission_grant_audit_scope_time ON pp_t_role_permission_grant_audit (new_scope_code, changed_at);
CREATE INDEX idx_pp_t_role_permission_grant_audit_event_time ON pp_t_role_permission_grant_audit (event_type, changed_at);
CREATE INDEX idx_pp_t_role_permission_grant_audit_correlation_id ON pp_t_role_permission_grant_audit (correlation_id);
CREATE INDEX idx_pp_t_role_permission_grant_audit_assigned_by ON pp_t_role_permission_grant_audit (assigned_by);
CREATE INDEX idx_pp_t_role_permission_grant_audit_revoked_by ON pp_t_role_permission_grant_audit (revoked_by);
CREATE INDEX idx_pp_m_user_address_user_id ON pp_m_user_address (user_id);
CREATE INDEX idx_pp_m_user_address_user_default ON pp_m_user_address (user_id, is_default);
CREATE INDEX idx_pp_m_user_address_city ON pp_m_user_address (city);
CREATE INDEX idx_pp_m_user_address_postal_code ON pp_m_user_address (postal_code);
CREATE INDEX idx_pp_m_category_parent_id ON pp_m_category (parent_category_id);
CREATE INDEX idx_pp_m_category_status ON pp_m_category (status_code);
CREATE INDEX idx_pp_m_category_parent_status ON pp_m_category (parent_category_id, status_code);
CREATE INDEX idx_pp_m_brand_status ON pp_m_brand (status_code);
CREATE INDEX idx_pp_m_product_organization_id ON pp_m_product (organization_id);
CREATE INDEX idx_pp_m_product_owner_user_id ON pp_m_product (owner_user_id);
CREATE INDEX idx_pp_m_product_org_owner_status ON pp_m_product (organization_id, owner_user_id, status_code);
CREATE INDEX idx_pp_m_product_category_id ON pp_m_product (category_id);
CREATE INDEX idx_pp_m_product_brand_id ON pp_m_product (brand_id);
CREATE INDEX idx_pp_m_product_status ON pp_m_product (status_code);
CREATE INDEX idx_pp_m_product_org_status ON pp_m_product (organization_id, status_code);
CREATE INDEX idx_pp_m_product_org_category_status ON pp_m_product (organization_id, category_id, status_code);
CREATE INDEX idx_pp_m_product_category_status ON pp_m_product (category_id, status_code);
CREATE INDEX idx_pp_m_product_brand_status ON pp_m_product (brand_id, status_code);
